### ISSUE TITLE
json decode error

### ISSUE THREAD

**Issue by pgwadapool** [QuixoteSystems/koios-python#2]
print(koios_python.get_address_info("addr1qyp9kz50sh9c53hpmk3l4ewj9ur794t2hdqpngsjn3wkc5sztv9glpwt3frwrhdrltjaytc8ut2k4w6qrx3p98zad3fq07xe9g"))

info = json.loads(info.content)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by QuixoteSystems** [comment]
Thanks a lot for open this issue. I got the problem. Koios have changed some queries and their methods, per example, get_address_info was a GET and now is a POST.

Right now I'm checking all library and fixing these problems because I notice that some more queries methods have changed. I will release a new version tomorrow, I hope.

**Comment by QuixoteSystems** [comment]
Now with new version 0.3.1 is all working fine. Just update your library with:

```
pip install --upgrade koios_python
```
